name: Docker Image CI

on:
  push:
    branches: [ "mainline" ]
  pull_request:
    branches: [ "mainline" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t session-manager-plugin-image .

    - name: Build the plugin
      run: docker run -it --rm --name session-manager-plugin -v `pwd`:/session-manager-plugin session-manager-plugin-image make release
